import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron, Moirai_One, Uncial_Antiqua, Major_Mono_Display } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron-google",
  subsets: ["latin"],
});

const moiraiOne = Moirai_One({
  weight: "400",
  variable: "--font-moirai-google",
  subsets: ["latin"],
});

const uncialAntiqua = Uncial_Antiqua({
  weight: "400",
  variable: "--font-uncial-google",
  subsets: ["latin"],
});

const majorMonoDisplay = Major_Mono_Display({
  weight: "400",
  variable: "--font-major-mono-google",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${moiraiOne.variable} ${uncialAntiqua.variable} ${majorMonoDisplay.variable} antialiased`}
      >
                <Navigation />
        
        {children}
                {/* Simple Footer */}
        <footer className="py-8 bg-black/50 backdrop-blur-md text-center border-t border-white/5 relative z-10 transition-colors">
          <p className="text-zinc-500 text-sm">© {new Date().getFullYear()} Alwin Eldhose. Built with Next.js & Tailwind CSS.</p>
        </footer>
      </body>
    </html>
  );
}
